#!/usr/bin/gawk -f
# This program takes variables in board.config
# and substitutes them into another file using
# @var@ as a pattern to find and replace
FNR==NR&&/^CONFIG/{
	split($0,line,"="); conf[line[1]]=line[2];
}
FNR!=NR{
	# TODO: this is a gawkism, but otherwise things
	# get quite cumbersome when trying to replace an arbitrary
	# number of patterns efficiently...
	if(match($0,/@([a-zA-Z0-9_]+)@/,matched)) {
		for (i=1;i in matched;i++)
			gsub(matched[0], conf["CONFIG_"matched[i]]);
	}
	print;
}
